### ISSUE TITLE
Rows.Next(): unusual behaviour

### ISSUE THREAD

**Issue by andvary** [360EntSecGroup-Skylar/excelize#644] opened 2020-05-24 10:18 UTC
I'm using excelize v2.1.0 with go 1.14 on Windows 10 x64. 

In one of my functions I call Rows.Next() without actually fetching data with Rows.Columns() to move the iterator and skip the first string (with headers). 

However, when I call "Rows.Columns()" within a "for Rows.Next()" loop afterwards, it still fetches the very first row, although (as far as I observe in the debugger output) the "curRow" counter is equal to "2". Am I misunderstanding the intended behaviour, or it is actually a bug?

Below is the sample code to illustrate the issue and the XLSX file I used for it: 

[sample.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/4673262/sample.xlsx)

```
package main

import (
	"fmt"

	"github.com/360EntSecGroup-Skylar/excelize"
)

func moveIterator () {
	f, err := excelize.OpenFile("sample.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	rows, err := f.Rows("Sheet1")
	if err != nil {
		fmt.Println(err)
		return
	}

	if !rows.Next() {
		fmt.Println("empty sheet")
	}

	for rows.Next() {
		row, err := rows.Columns()
		if err != nil {
			fmt.Println(err)
		}
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}
}

func moveIteratorAndFetchData () {
	f, err := excelize.OpenFile("sample.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	rows, err := f.Rows("Sheet1")
	if err != nil {
		fmt.Println(err)
		return
	}

	if !rows.Next() {
		fmt.Println("empty sheet")
	}
	_, _ = rows.Columns()

	for rows.Next() {
		row, err := rows.Columns()
		if err != nil {
			fmt.Println(err)
		}
		for _, colCell := range row {
			fmt.Print(colCell, "\t")
		}
		fmt.Println()
	}
}

func main () {
	// In this case, upon calling rows.Next, curRow increments, but rows.Columns, called within the "for rows.Next" loop
	// produces "a b" (first row) instead of the second ("c d")
	moveIterator()

	// This function is absolutely identical to the previous, except for "_, _ = rows.Columns()", however it produces "c d"
	moveIteratorAndFetchData()
}
```

**Comment by xuri** [comment] 2020-05-25 10:46
Thanks for your feedback. Each call of `rows.Columns()` will read a row, `Next` just used to check if the end of the streaming.

**Comment by gitdlam** [comment] 2020-09-01 12:53
I just encountered the same behaviour and was surprised.  I was intentionally skipping a number of rows because i knew the data i need, were not in those rows.  Now i call .Columns() and just not use the data.

**Comment by xuri** [comment] 2020-10-03 15:25
I think this is expected behavior, so I'll close this issue, if you have any questions, please let me know.

**Closed by xuri** 2020-10-03 15:25 UTC
