### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ofhydrogen** [360EntSecGroup-Skylar/excelize#716] opened 2020-10-21 14:05 UTC
Hello! Looks like method GetCellValue have a memory leak

This is a memory usage when I call GetCellValue in a loop
![image](https://user-images.githubusercontent.com/12169356/96730168-9b96d700-13be-11eb-9d5c-c5103e543431.png)

and with random string instead of GetCellValue
![image](https://user-images.githubusercontent.com/12169356/96730516-e87aad80-13be-11eb-8d0b-afb6fcdb4e76.png)

Code:
``` 
var value string
for _, attrId := range attrIDs {
			cell, err = excelize.CoordinatesToCellName(col, row)
			if err != nil {
				return 0, false, err
			}
			value, err = f.GetCellValue(category_sheets.ItemsSheetName, cell)
			if err != nil {
				return 0, false, err
			}
			value = strings.TrimSpace(value)
			values[attrId] = value
			col++
		}
```

Go ver:  1.15
Lib ver: 2.1.0

**Comment by xuri** [comment] 2020-10-22 02:43
Thanks for your feedback, I have tested memory usage of GetCellValue, and it seems to like stable, could you provide more details code and spreadsheet attachment without confidential?

**Comment by ofhydrogen** [comment] 2020-10-22 11:20
```
func (s *XlsImportService) parseAndCreateItems(ctx context.Context, f *excelize.File, task *model.Task, parsed *docType, template *model.CategoryTemplate) error {
	attrIDs, err := collectAttrIDs(f, category_sheets.ItemsSheetName, parsed.config.AttributeRowNumber)
	if err != nil {
		return err
	}

	var buffer []rowType
	// values
	serNum := int64(0)
	values := make(map[string]string)
	var value string
	var cell string
	col := 1
	var i rowType
	for row := parsed.config.ValuesRowNumber; ; row++ {
		col = 1
		for _, attrId := range attrIDs {
			cell, err = excelize.CoordinatesToCellName(col, row)
			if err != nil {
				return err
			}
			value, err = f.GetCellValue(category_sheets.ItemsSheetName, cell)
			if err != nil {
				return err
			}
			value = strings.TrimSpace(value)
			values[attrId] = value
			col++
		}

		if allEmpty(values) {
			if len(buffer) > 0 {
				err = s.sendRows(ctx, task.DocumentId, parsed, buffer, template)
				if err != nil {
					return err
				}
			}
			break
		}

		i = rowType{
			SerNum: serNum,
			Values: values,
		}
		buffer = append(buffer, i)
		serNum++

		if len(buffer) >= parseItemsBatchSize {
			logger.Errorf(ctx, "SER NUM: %d", serNum)
			logger.Errorf(ctx, "LEN BUF: %d", len(buffer))
			PrintMemUsage(9)
			err = s.sendRows(ctx, task.DocumentId, parsed, buffer, template)
			if err != nil {
				return err
			}
			buffer = nil
		}
	}

	return nil
}
```

[ШШШ.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/5422313/default.xlsx)

**Comment by xuri** [comment] 2020-10-28 13:55
I think the memory usage growth may be caused by buffer append, I suggest profiling your program by [`pprof`](https://blog.golang.org/pprof)
 to get more details.

**Comment by franklwel1990** [comment] 2020-10-31 03:07
Encountered the same problem

**Comment by xuri** [comment] 2020-11-03 08:21
Could you provide any details?

**Comment by xuri** [comment] 2020-11-10 12:38
I close this issue and welcome left comments if you have any more questions.

**Closed by xuri** 2020-11-10 12:38 UTC
Labels: needs more info

**Comment by ofhydrogen** [comment] 2020-12-18 09:43
Hello! The problem still exists. Any possibilities to fix it?
