### ISSUE TITLE
xlsx.RemoveRow(“sheet1”, n) caused file corrupted

### ISSUE THREAD

**Issue by billytoe** [360EntSecGroup-Skylar/excelize#372] opened 2019-03-27 13:02 UTC
xlsx.RemoveRow(“sheet1”, 1) 
xlsx.RemoveRow(“sheet1”, 3) 
xlsx.RemoveRow(“sheet1”, 9) 
xlsx.Save()

应该怎么删除 才能 正确并不损坏文件 删除呢？

**Comment by xuri** [comment] 2019-03-29 03:25
Hi @billytoe, thanks for your issue. Please provides the version of excelize and Go you are using, and the xlsx file attachment if you can. Note that [in the godoc](https://godoc.org/github.com/360EntSecGroup-Skylar/excelize#File.RemoveRow): use `RemoveRow` with caution, which will affect changes in references such as formulas, charts, and so on. If there is any referenced value of the worksheet, it will cause a file error when you open it. The excelize only partially updates these references currently.

**Comment by billytoe** [comment] 2019-03-29 11:13
[TEST01 - 副本 (1).xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3022364/TEST01.-.1.xlsx)
[TEST01 - 副本 (3) 删除后损坏.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3022365/TEST01.-.3.xlsx)
[TEST01 - 副本 (2) AC列加删除字样.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3022366/TEST01.-.2.AC.xlsx)

go 1.11
360EntSecGroup-Skylar/excelize 版本 是 20190328 更新的

TEST01 - 副本 (3) 删除后损坏.xlsx 是损坏的文件

**Comment by xuri** [comment] 2019-03-29 12:36
HI @billytoe, please follow by issue template provide code and steps to reproduce the issue.

**Comment by imansohibul** [comment] 2019-08-20 06:31
#### Description
Hallo, i found the same issue. ```RemoveRow``` seems to be corrupting spreadsheets. 

#### Steps to reproduce the issue:
In my case,  i have an excel file with the following merged cells:
- ```mergeCell ref="D25:F25"```
- ```mergeCell ref="D26:F26"```
- ```mergeCell ref="D27:F27"```
- ```mergeCell ref="D28:F28"```
- ```mergeCell ref="D24:F24"```

Let say, the row 26 would like to be removed,  and execute the following pseudocode below:

```go
func main() {
	var (
		file *excelize.File
		err  error
	)
	// open the file
	file, err = excelize.OpenFile("testlocal.xlsx")
	panic(err)

	file.RemoveRow("sheet1",  26)
	file.Save()
}
```

#### Describe the results you received
When i open the file, i receive the message "We found a problem with some content in "testlocal.xlsx" Do you want us to try to recover as much as we can?" after clicking yes, it will go to a dialog box that it has been repair/recovered. 

Repair Log:
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">

<logFileName>error009680_03.xml</logFileName>

<summary>Errors were detected in file 'D:\Documents\test.xlsx'</summary>


-<removedRecords>

<removedRecord>Removed Records: Merge cells from /xl/worksheets/sheet1.xml part</removedRecord>

</removedRecords>

</recoveryLog>
```

I try to check deeper to examining  the ```/xl/worksheets/sheet1.xml``` file, showed the merged cell node was added twice:
```
<mergeCells>
   <mergeCell ref="D26:F26"/>
   <mergeCell ref="D26:F26"/>
</mergeCells>
```

After "repairing" the file, the duplicate node was removed:
```
<mergeCells>
   <mergeCell ref="D26:F26"/>
</mergeCells>
```

#### Describe the results you expected:
i expect the row to be removed without error

#### Output of ```go version```:
go version go1.12.1 darwin/amd64

#### Excelize version or commit ID:
Version: v1.4.0
Commit ID: https://github.com/360EntSecGroup-Skylar/excelize/commit/3e004d900b103379c2d62657a3070de4a2e8585a

#### Environment details (OS, Microsoft Excel™ version, physical, etc.):
Windows 10, MS Excel 2016

**Comment by xuri** [comment] 2020-03-19 10:16
Hi @billytoe, sorry for my late reply. I have tested with the attachments your upload with the code at version [cea3d80](https://github.com/360EntSecGroup-Skylar/excelize/tree/cea3d806ecbec5027a8f0d7f10b700707131a7be), and it works well. Please try to use the master branch code.

Hi @imansohibul, could you try to use the master branch code? If still got corrupted file, please provide `testlocal.xlsx` as an attachment.

**Comment by billytoe** [comment] 2020-03-23 04:30
太好了

**Comment by billytoe** [comment] 2020-03-23 04:31
> 嗨@billytoe，很抱歉我的回复很晚。我已经使用[cea3d80](https://github.com/360EntSecGroup-Skylar/excelize/tree/cea3d806ecbec5027a8f0d7f10b700707131a7be)版本的代码对您上传的附件进行了测试，并且效果很好。请尝试使用master分支代码。
> 
> @imansohibul，太好啦。

**Comment by xuri** [comment] 2020-10-03 15:31
I'll close this issue, if you have any questions, please let me know.

**Closed by xuri** 2020-10-03 15:31 UTC
Labels: needs more info
