### ISSUE TITLE
cpu keep 100 usage

### ISSUE THREAD

**Issue by caotian** [360EntSecGroup-Skylar/excelize#806] opened 2021-03-15 03:35 UTC
cpu keep 100 usage for production use

code:

	uploadFile, err := uploadFileHandler.Open()
	excelFile, err := excelize.OpenReader(uploadFile)
	if err != nil {
		return
	}

	firstSheet := excelFile.GetSheetName(0)
	if firstSheet == "" {
		return
	}

	rows, err := excelFile.GetRows(firstSheet)
    ...

working perfectly on test, but cpu keep 100 usage when online for production use

go pprof profile:

![QQ20210315-112650](https://user-images.githubusercontent.com/3139199/111099862-65cad880-8581-11eb-9628-2bb2263eae9f.png)
![QQ20210315-112533](https://user-images.githubusercontent.com/3139199/111099875-695e5f80-8581-11eb-9067-7c8874068092.png)
![QQ20210315-112823](https://user-images.githubusercontent.com/3139199/111099960-97dc3a80-8581-11eb-94b7-93227f8e274a.png)

using in docker container, excelize v2.3.2

**Comment by xuri** [comment] 2021-03-15 04:32
Thanks for your feedback, could you provide more details or a spreadsheet xlsx attachment without confidential info?

**Comment by caotian** [comment] 2021-03-15 05:22
It's run online, many users uploaded excel files to parse, i can not distinguish which excel file cause this problem.
I had test so many times, this issure nerver happened,  so i had to restart the online service, then it can run normaly for several hours or days.

**Comment by xuri** [comment] 2021-03-15 05:28
Maybe you have received a spreadsheet containing an amount of data, try to add the limit for received files that can be processed according to your hardware environment.

**Comment by caotian** [comment] 2021-03-15 05:29
ok, thanks, I'll have a try.

**Comment by xuri** [comment] 2021-03-30 02:33
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know.

**Closed by xuri** 2021-03-30 02:33 UTC
Labels: needs more info

**Comment by guantou-coffee** [comment] 2022-05-24 07:18
Same issues. And also can't find specific file cause this. 
Have you find the reason and figure out this problem?
