### ISSUE TITLE
Poor performance when MergeCell and SetCellValue In a for loop

### ISSUE THREAD

**Issue by liov** [360EntSecGroup-Skylar/excelize#595] opened 2020-03-16 05:45 UTC
**Description**

**Steps to reproduce the issue:**
when MergeCell and SetCellValue In a for loop,I waited for 10 minutes and still didn't export
```go
for _, order := range *res.Data.OrderListInfos {
		for _, good := range order.OrderSkus {
			headerRow++
			f.SetRowHeight("Sheet1", headerRow, 30)
			headerRowStr = strconv.Itoa(headerRow)
			f.SetCellValue("Sheet1", column[3]+headerRowStr, good.ProductName)
                        ...
		}
		//合并单元格
		if len(order.OrderSkus) != 1 {
			for j := 0; j < 3; j++ {
				f.MergeCell("Sheet1", column[j]+strconv.Itoa(headerRow-len(order.OrderSkus)+1), column[j]+headerRowStr)
			}
		}
		if len(order.OrderSkus) != 1 {
			for j := 11; j <= 27; j++ {
//在for中用strconv.Itoa也是性能很差的原因之一，然而改了作用微乎其微
				f.MergeCell("Sheet1", column[j]+strconv.Itoa(headerRow-len(order.OrderSkus)+1), column[j]+headerRowStr)
			}
		}
		currentRow := headerRow - len(order.OrderSkus) + 1
		currentRowStr := strconv.Itoa(currentRow)
		f.SetCellValue("Sheet1", column[0]+currentRowStr, order.OrderInfo.OrderId)
		f.SetCellValue("Sheet1", column[2]+currentRowStr, order.OrderInfo.UserId)
		f.SetCellValue("Sheet1", column[20]+currentRowStr, order.OrderInfo.Name)
		f.SetCellValue("Sheet1", column[21]+currentRowStr, order.OrderInfo.Phone)
               ...
	}
```
i rewrite it in two for loop,only 7seconds
```go
 	for _, order := range *res.Data.OrderListInfos {
		for _, good := range order.OrderSkus {
			headerRow++
			f.SetRowHeight("Sheet1", headerRow, 30)
			headerRowStr = strconv.Itoa(headerRow)
			f.SetCellValue("Sheet1", column[3]+headerRowStr, good.ProductName)
                        ...
		}

		currentRow := headerRow - len(order.OrderSkus) + 1
		currentRowStr := strconv.Itoa(currentRow)
		f.SetCellValue("Sheet1", column[0]+currentRowStr, order.OrderInfo.OrderId)
                ...
	}
	headerRow = 2
	for _, order := range *res.Data.OrderListInfos {
		//合并单元格
		if len(order.OrderSkus) != 1 {
			headerRowStr = strconv.Itoa(headerRow)
			mergerRow := strconv.Itoa(headerRow + len(order.OrderSkus) - 1)
			for j := 0; j < 3; j++ {
				f.MergeCell("Sheet1", column[j]+mergerRow, column[j]+headerRowStr)
			}
			for j := 11; j <= 27; j++ {
				f.MergeCell("Sheet1", mergerRow, column[j]+headerRowStr)
			}
		}
		headerRow += len(order.OrderSkus)
	}
```
**Describe the results you received:**
5000rows need ten min over
**Describe the results you expected:**
less than 10s
**Output of `go version`:**

```text
1.14
```

**Excelize version or commit ID:**

```text
2.10
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
windows10

**Comment by xuri** [comment] 2020-03-16 08:54
Hi @liov, please excludes performance issues caused by the potential in the above code (such as complexity), providing a clear and concise code will helpful for us quickly resolve the issue. I'll close this issue, and if you still have other questions, please reopen it.

**Closed by xuri** 2020-03-16 08:54 UTC

**Comment by liov** [comment] 2020-03-18 10:49
我能用中文说明问题吗，下面是一份可以直接执行的代码，当合并单元格和设置值在一个for循环中，性能特别差，分开写性能则会高很多
```go
type Foo struct {
	A, B, C string
	D       []string
}

var column = [...]string{"A", "B", "C", "D"}

func main() {
	datas := make([]Foo, 1000)
	for i := range datas {
		datas[i].A = "A"
		datas[i].B = "B"
		datas[i].C = "C"
		datas[i].D = make([]string, 3)
		for j := range datas[i].D {
			datas[i].D[j] = "D"
			datas[i].D[j] = "E"
			datas[i].D[j] = "F"
		}
	}
	inOneForLoop(datas)
	inTwoForLoop(datas)
}

func inOneForLoop(datas []Foo) {
	defer func(t time.Time) {log.Println("inOneForLoop",time.Now().Sub(t))}(time.Now())
	f := excelize.NewFile()
	style, err := f.NewStyle(`{"alignment":{"horizontal":"center","vertical":"center"}}`)
	f.SetColStyle("Sheet1", "A:D", style)
	if err != nil {
		log.Println(err)
	}
	var headerRow = 0
	var headerRowStr string
	for _, data := range datas {
		for _, sub := range data.D {
			headerRow++
			f.SetRowHeight("Sheet1", headerRow, 30)
			headerRowStr = strconv.Itoa(headerRow)
			f.SetCellValue("Sheet1", column[3]+headerRowStr, sub)
		}
		//合并单元格
		if len(data.D) != 1 {
			for j := 0; j < 3; j++ {
				f.MergeCell("Sheet1", column[j]+strconv.Itoa(headerRow-len(data.D)+1), column[j]+headerRowStr)
			}
		}
		currentRow := headerRow - len(data.D) + 1
		currentRowStr := strconv.Itoa(currentRow)
		f.SetCellValue("Sheet1", column[0]+currentRowStr, data.A)
		f.SetCellValue("Sheet1", column[1]+currentRowStr, data.B)
		f.SetCellValue("Sheet1", column[2]+currentRowStr, data.C)
	}
	f.SaveAs("./test.xlsx")
}

func inTwoForLoop(datas []Foo) {
	defer func(t time.Time) {log.Println("inTwoForLoop",time.Now().Sub(t))}(time.Now())
	f := excelize.NewFile()
	style, err := f.NewStyle(`{"alignment":{"horizontal":"center","vertical":"center"}}`)
	f.SetColStyle("Sheet1", "A:D", style)
	if err != nil {
		log.Println(err)
	}
	var headerRow = 0
	var headerRowStr string
	for _, data := range datas {
		for _, sub := range data.D {
			headerRow++
			f.SetRowHeight("Sheet1", headerRow, 30)
			headerRowStr = strconv.Itoa(headerRow)
			f.SetCellValue("Sheet1", column[3]+headerRowStr, sub)
		}
		currentRow := headerRow - len(data.D) + 1
		currentRowStr := strconv.Itoa(currentRow)
		f.SetCellValue("Sheet1", column[0]+currentRowStr, data.A)
		f.SetCellValue("Sheet1", column[1]+currentRowStr, data.B)
		f.SetCellValue("Sheet1", column[2]+currentRowStr, data.C)
	}
	headerRow = 1
	for _, data := range datas {
		headerRowStr = strconv.Itoa(headerRow)
		mergerRow := strconv.Itoa(headerRow + len(data.D) - 1)
		if len(data.D) != 1 {
			for j := 0; j < 3; j++ {
				f.MergeCell("Sheet1", column[j]+mergerRow, column[j]+headerRowStr)
			}
		}
		headerRow += len(data.D)
	}
	f.SaveAs("./test1.xlsx")
}

```

**Comment by liov** [comment] 2020-03-18 10:52
讲真的，这样直接关闭issues很不好

**Comment by liov** [comment] 2020-03-18 10:54
> Hi @liov, please excludes performance issues caused by the potential in the above code (such as complexity), providing a clear and concise code will helpful for us quickly resolve the issue. I'll close this issue, and if you still have other questions, please reopen it.
我并没有权限重新打开

**Comment by xuri** [comment] 2020-03-18 16:22
Hi @liov, thanks for your feedback.

In the `inOneForLoop` function, there two operations execute as alternately: setting the cell value and merging the cell. In order to ensure the compatibility of the document format, Excelize needs to do some checks before setting the cell each time to ensure that the cell to be set this time is compatible with existing merged cells (style, property inheritance, etc.), which will cause multiple internal function [`checkCellInArea`](https://github.com/360EntSecGroup-Skylar/excelize/blob/cea3d806ecbec5027a8f0d7f10b700707131a7be/cell.go#L604-L622) calls.

In the `inTwoForLoop` function, two operations execute as separates, and the `SetCellValue` is before the `MergeCell` operation. Since there are no merged cells in the worksheet at this time, which reduced the process of merged cells inspection.

To ensure document format compatibility, I propose to hold these internal checks and look for other potential performance optimizations methods. I got that you're unable to reopen the issue, I'm sorry for my closing the issue before.

----

在 `inOneForLoop` 函数中，设置单元格的值与合并单元格操作交替进行，为保证文档格式兼容，每次设置单元格前，Excelize 需要做一些列检查，以确保本次即将设置的单元格与已存在的合并单元格相互兼容（样式、属性继承等处理），这将引起内部函数 [`checkCellInArea`](https://github.com/360EntSecGroup-Skylar/excelize/blob/cea3d806ecbec5027a8f0d7f10b700707131a7be/cell.go#L604-L622) 的多次调用。

在 `inTwoForLoop` 函数中，设置单元格的值与合并单元格两个操作分开进行，并且 `SetCellValue` 在 `MergeCell` 操作前执行，由于此时工作表内不存在任何合并单元格，避免了大量的合并单元格检查过程。

为了保证文档格式兼容性，我提议仍然保留这些内部检查，并寻找其他潜在的性能优化方式。得知您无法重新开启此 issue，我对先行关闭 issue 表示抱歉。

**Comment by liov** [comment] 2020-03-18 16:32
Thank you for your answer

**Comment by liov** [comment] 2020-11-18 08:38
![image](https://user-images.githubusercontent.com/23721020/99505647-0d614100-29bc-11eb-8736-134aa72d97ed.png)
![image](https://user-images.githubusercontent.com/23721020/99505996-7f398a80-29bc-11eb-8514-fdb8dce6128a.png)
实在抱歉，竟然还是这个问题，我采用的是第二种写法，才发现就是合并单元格的性能问题
