### ISSUE TITLE
I can't access the Repo

### ISSUE THREAD

**Issue by lucaseduardobr** [360EntSecGroup-Skylar/excelize#828] opened 2021-04-25 17:12 UTC
**Description**

**Steps to reproduce the issue:**
1.  I tried " go get github.com/360EntSecGroup-Skylar/excelize/v2"

**Describe the results you received:**

$ go get github.com/360EntSecGroup-Skylar/excelize/v2
go get: module github.com/360EntSecGroup-Skylar/excelize/v2: git ls-remote -q origin in C:\Users\lucas\go\pkg\mod\cache\vcs\f283cc5f286f11219a1ea01eea7a98100c7ee3feeec3fec8d4dc1ee0ea2eeb40: exit status 128:
        ssh: Could not resolve hostname github.com:360EntSecGroup-Skylar: Name or service not known
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.

**Describe the results you expected:**

Downloaded Repo

**Output of `go version`:**

```text
go: errors parsing go.mod:
c:\Users\lucas\Desktop\Cogsworth-master\go.mod:8:2: require github.com/360EntSecGroup-Skylar/excelize: git ls-remote -q origin in C:\Users\lucas\go\pkg\mod\cache\vcs\f283cc5f286f11219a1ea01eea7a98100c7ee3feeec3fec8d4dc1ee0ea2eeb40: exit status 128:
	ssh: Could not resolve hostname github.com:360EntSecGroup-Skylar: Name or service not known
	fatal: Could not read from remote repository.
	
	Please make sure you have the correct access rights
	and the repository exists.
```

**Excelize version or commit ID:**

```text
I don't have one
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

User Name:                              DESKTOP-N55G5UM
Name of searching system :              Microsoft Windows 10 Famille
System version :                         10.0.19042 N/A build 19042
Produced               :        Microsoft Corporation

git version 2.31.1.windows.1

go version go1.16.3 windows/amd64

**Comment by xuri** [comment] 2021-04-26 02:42
Please give a try to clone the repo by HTTPS or SSH protocol, or download the source code from [master branch](https://github.com/xuri/excelize/archive/refs/heads/master.zip) or release page.

**Comment by xuri** [comment] 2021-05-06 10:16
This issue may be caused by networks and it seems not in the scope of this library, so I'll close this issue,  if you have any questions, please let me know.

**Closed by xuri** 2021-05-06 10:16 UTC
