### ISSUE TITLE
Delete sheet breaks AutoFilter 

### ISSUE THREAD

**Issue by pandaadb** [360EntSecGroup-Skylar/excelize#775] opened 2021-02-01 11:44 UTC
**Description**

When using autoFilter, removing `Sheet1` seems to be breaking the entire file. 

This is tested with `LibreOffice` on ubuntu. 

When uploaded to Office365, it says the file has been repaired. 

**Steps to reproduce the issue:**

Code: 

```
        f := excelize.NewFile()

	f.NewSheet("sheet_test")
	for i := 0; i < 5; i++ {
		idx, _ := excelize.CoordinatesToCellName(i+1, 1)
		f.SetCellValue("sheet_test", idx, fmt.Sprintf("Header %d", i))
	}

	row := 2

	for j := 0; j < 10; j++ {

		for i := 0; i < 5; i++ {
			idx, _ := excelize.CoordinatesToCellName(i+1, row)
			f.SetCellValue("sheet_test", idx, fmt.Sprintf("Value %d", i))
		}

		row++
	}

	f.AutoFilter("sheet_test", "A1", "E11", "")

	f.DeleteSheet("Sheet1")
	f.SetActiveSheet(0)

	filename := "/tmp/test4.xlsx"

	f.SaveAs(filename)
```

**Describe the results you received:**

When opening the file, Libre office reports: 

```
General input/output error
```

**Describe the results you expected:**

A 1 sheet xlsx file, containing the Autofilter. 

**Output of `go version`:**

```text
go version go1.13.10 linux/amd64
```

**Excelize version or commit ID:**

```text
github.com/360EntSecGroup-Skylar/excelize/v2 v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Ubuntu 18.04
LibreOffice  (LibreOffice 6.0.7.3 00m0(Build:3)

**Comment by xuri** [comment] 2021-02-01 11:54
Thanks for your issue. As the docs of the `DeleteSheet` noticed, this issue caused by some references not removed after deleting the worksheet which has the auto filter, I'll consider resolving it.

**Comment by pandaadb** [comment] 2021-02-01 12:12
Oh that makes sense. I am sorry, I hadn't read the docs on DeleteSheet! 

A question, is there a "safe" way to create a new spreadsheet without the first Sheet? I resolved to removing it because I had no idea how to get rid off it :)

**Comment by xuri** [comment] 2021-02-01 12:18
If you needn't the default worksheet named `Sheet1`, you can rename it by `SetSheetName("Sheet1", "sheet_test")` before coming up with operations.

**Closed** 2021-02-02 14:23 UTC
Labels: in progress

**Comment by xuri** [comment] 2021-02-02 14:26
I have fixed it, please try to use the master branch code, and this patch will be released in the next version.
