### ISSUE TITLE
v2.3.2 generates empty worksheets, but works in v2.3.1

### ISSUE THREAD

**Issue by SVilgelm** [360EntSecGroup-Skylar/excelize#813] opened 2021-04-02 16:50 UTC
**Description**

In case of writing data to a new worksheet and then deleted "Sheet1" (default one), the final file has no data at all

**Steps to reproduce the issue:**
1. Create new file
2. Create new sheet
3. Write data to the newly created sheet
4. Delete default "Sheet 1"
5. Save file

**Describe the results you received:**

empty file

**Describe the results you expected:**

file with my data

**Output of `go version`:**

```text
go version go1.16.2 darwin/amd64
```

**Excelize version or commit ID:**

```text
v2.3.2
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
System: MacOS
Use Numbers to open the files

**Snippet**

```go
package main

import (
	"fmt"
	"math/rand"

	"github.com/360EntSecGroup-Skylar/excelize/v2"
)

func main() {
	file := excelize.NewFile()
	file.NewSheet("No Default Sheet")
	streamWriter, err := file.NewStreamWriter("No Default Sheet")
	if err != nil {
		fmt.Println(err)
	}
	styleID, err := file.NewStyle(`{"font":{"color":"#777777"}}`)
	if err != nil {
		fmt.Println(err)
	}
	if err := streamWriter.SetRow("A1", []interface{}{
		excelize.Cell{StyleID: styleID, Value: "Data"},
	}); err != nil {
		fmt.Println(err)
	}
	for rowID := 2; rowID <= 30; rowID++ {
		row := make([]interface{}, 50)
		for colID := 0; colID < 50; colID++ {
			row[colID] = rand.Intn(640000)
		}
		cell, _ := excelize.CoordinatesToCellName(1, rowID)
		if err := streamWriter.SetRow(cell, row); err != nil {
			fmt.Println(err)
		}
	}
	if err := streamWriter.Flush(); err != nil {
		fmt.Println(err)
	}

	file.DeleteSheet("Sheet1")

	if err := file.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}
}
```

This code works well with v2.3.1, but does not work in v2.3.2
If I remove the line `file.DeleteSheet("Sheet1")`, then the "No Default Sheet" contains the data, otherwise it's empty

**Comment by SVilgelm** [comment] 2021-04-02 16:57
I checked the `master` branch, result is same, no data

**Comment by SVilgelm** [comment] 2021-04-02 19:52
same happens if replace `DeleteSheet` with `UpdateLinkedValue`:
```go
	if err := file.UpdateLinkedValue(); err != nil {
		fmt.Println(err)
	}
```
no errors, but the sheet is empty, even if the default name is used

**Comment by xuri** [comment] 2021-04-03 02:37
Thanks for your feedback, I confirmed this issue caused by PR #659, and I'll fix it tomorrow.

**Comment by xuri** [comment] 2021-04-03 14:56
Thanks for your feedback, I confirmed this issue caused by PR #659, and I have fixed it, please try to use the master branch code, and this patch will be released in the next version.

**Closed** 2021-04-03 14:56 UTC
Labels: confirmed

**Comment by SVilgelm** [comment] 2021-04-03 15:32
Confirm, the issue is fixed!
