### ISSUE TITLE
PR 366 Documentation

### ISSUE THREAD

**Issue by mlh758** [360EntSecGroup-Skylar/excelize#360] opened 2019-03-19 18:33 UTC
**Description**

#366 Removed ToAlphaString, which is a breaking change, and replaced it with ColumnNumberToName. The [documentation](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/lib.go#L159) however, still has the original name in it. It also changed the signature from a string return value to a `(string, error)` return value to guard against indexes less than one. This doesn't seem necessary.

It also appears to have changed the zero based index to a one based index. What was the motivation for these changes?

Will there be a changelog that lays out other things that are now broken from that PR? It would be helpful to know what the upgrade path looks like.

**Comment by mlh758** [comment] 2019-03-19 18:36
For an example of why a zero based index and a single return value was nice:
```
for colNum, str := range headers {
    s.workbook.SetCellStr(sheetName, fmt.Sprintf("%s%d", excelize.ToAlphaString(colNum), rowNum), str)
}
```

Code now has to be more verbose to introduce an offset and ignore the error.

**Comment by mlh758** [comment] 2019-03-19 19:14
`setRowOutlineLevel` now panics instead of returning, or returning an error like `ColumnNumberToName` does. It would be nice if the behavior was consistent.

**Comment by mlh758** [comment] 2019-03-19 21:22
`AddPicture` is doing some weird things now. Prior to this change I was merging cells `A1` to `B4` then placed an image in cell `A1` with some x and y scaling. It sat nicely in the cell. After this change, it no longer sits in the cell but looks like the top left corner is centered now instead. Also, there appear to be infinite copies of the image.

![image](https://user-images.githubusercontent.com/4331955/54642637-1bcabd00-4a63-11e9-8e85-45d10357ce38.png)

If I click and drag the image from where it sits originally, more appear and they just keep appearing!

**Comment by xuri** [comment] 2019-03-20 07:52
> **Description**
> 
> #366 Removed ToAlphaString, which is a breaking change, and replaced it with ColumnNumberToName. The [documentation](https://github.com/360EntSecGroup-Skylar/excelize/blob/master/lib.go#L159) however, still has the original name in it. It also changed the signature from a string return value to a `(string, error)` return value to guard against indexes less than one. This doesn't seem necessary.
> 
> It also appears to have changed the zero based index to a one based index. What was the motivation for these changes?
> 
> Will there be a changelog that lays out other things that are now broken from that PR? It would be helpful to know what the upgrade path looks like.

The `ToAlphaString` in the document has been updated to `ColumnNumberToName`
The motivation for consistent col/row index, refer to issues #349, #350 and #356
All API change will be included in the next version 1.5.0 and prompting upgrade API compatibility for the existing users in release notes

**Comment by xuri** [comment] 2019-03-20 08:16
> `AddPicture` is doing some weird things now. Prior to this change I was merging cells `A1` to `B4` then placed an image in cell `A1` with some x and y scaling. It sat nicely in the merged cell. After this change, it no longer sits in the cell but looks like the top left corner is centered now instead. Also, there appear to be infinite copies of the image.
> 
> ![image](https://user-images.githubusercontent.com/4331955/54642637-1bcabd00-4a63-11e9-8e85-45d10357ce38.png)
> 
> If I click and drag the image from where it sits originally, more appear and they just keep appearing!

Confirm that this is a problem caused by PR #356 and I will fix it.

**Closed** 2019-03-20 08:52 UTC

**Comment by mlh758** [comment] 2019-03-20 13:06
Since you're introducing several breaking changes you might want to consider bumping the library to v2. Most consumers probably assume you're following semantic versioning and would be surprised to have their code not compile after taking a minor version upgrade.

Thank you for Fixing the picture thing!

**Comment by xuri** [comment] 2019-03-21 05:03
> I pulled down your changes and tested them. Images are indeed going to the right place again. However, I'm still seeing the infinite image duplication issue. If I switch back to the previous version of excelize and drag an image around the workbook it simply moves the image. Now a copy is created and moved instead.

I didn't reproduce this situation. Could you provide file attachments and codes?

**Comment by xuri** [comment] 2019-03-21 05:21
> Since you're introducing several breaking changes you might want to consider bumping the library to v2. Most consumers probably assume you're following semantic versioning and would be surprised to have their code not compile after taking a minor version upgrade.
> 
> Thank you for Fixing the picture thing!

After consideration, I think all incompatible  API changes will be included in `v2.0.0`. If so we can modify function signature to using return error instead of panic. Kind notice @albenik

**Comment by albenik** [comment] 2019-03-21 07:18
@mlh758 Thank you for you feedback.
The primary motivation of col/row addressing changes was fact that different public methods used different addressing some-time zero-based, some-time one-based.

What about row starting number: Then I working with row number 5 which has label "5" in excel app and which addressed ad "A5" (for example) in this library, I am expecting that in all other places it will be «5» not «4». Also about column name to number conversions: Excel has numeric column mode, and columns also starting from "1" in this case.

**Comment by albenik** [comment] 2019-03-21 07:23
@mlh758 

> `setRowOutlineLevel` now panics instead of returning, or returning an error like `ColumnNumberToName` does. It would be nice if the behavior was consistent.
> 
> Given that setting the outline level now panics, I think it would be reasonable to have `ColumnNumberToName` also panic. Sending a valid column number seems like a reasonable requirement and returning an error value seems unnecessary just to ensure the parameter is a positive number. It's also not checking that the column number is less than the maximum of (I think) 16,384.
> 
> `setRowOutlineLevel` is also now 1 based index instead of 0 based. This is less surprising to a newcomer, but breaks a lot of code and could have been mitigated by just updating the docs instead of a code change.

Please look at https://golang.org/pkg/regexp where used complex approach: Functions returns errors and it `Must*` wrappers panics on error.

I used same approach here, but unfortunately I miss some wrappers for `ColumnNameToNubmer` for example.

I will be very pleasure I you made a PR with fix.

**Comment by albenik** [comment] 2019-03-21 07:32
> > Since you're introducing several breaking changes you might want to consider bumping the library to v2. Most consumers probably assume you're following semantic versioning and would be surprised to have their code not compile after taking a minor version upgrade.
> > Thank you for Fixing the picture thing!
> 
> After consideration, I think all incompatible API changes will be included in `v2.0.0`. If so we can modify function signature to using return error instead of panic. Kind notice @albenik

As I already proposed v2 earlier, agreed of course!
But we need to take care with https://github.com/golang/go/wiki/Modules#semantic-import-versioning to keep support for earler versions fo go. (Simply add `/v2`  suffix to package name not enough, `v2` branch also needed.

**Comment by albenik** [comment] 2019-03-21 07:33
@xuri And go away from panics and use error will be good solution i think.

**Comment by mlh758** [comment] 2019-03-21 12:16
I'll open a new issue for the image duplication thing once I have
everything together to reproduce it in a smaller test case.

**Comment by mlh758** [comment] 2019-03-21 13:50
> The primary motivation of col/row addressing changes was fact that different public methods used different addressing some-time zero-based, some-time one-based.

I certainly understand the benefit of making the numbering consistent, it was just alarming to see the change suddenly appear without any discussion when having better documentation on the functions could have resolved most issues with using the library. I prefer the new names you've introduced - `ColumnNumberToName` is more descriptive than `ToAlphaString`.

The difference between what this library is doing an the regexp library though is that `ColumnNumberToName` is more of an array access by index than dynamically building string for a regular grammar. If you access an invalid array index Go panics, I think that would be reasonable to expect here as well.

To elaborate more, returning error values from things that you would expect to fail - system calls, HTTP requests, parsing operations - makes a lot of sense and his helpful. When you're only checking that the number is within some fixed range I'm not sure it's providing much value here.

**Comment by albenik** [comment] 2019-03-21 16:13
> I  certainly understand the benefit of making the numbering consistent, it was just alarming to see the change suddenly appear without any discussion

@mlh758 Your absolutely right here!

But I have to improve library for real project with very hard deadline.

For me the only two way where possible: 
1. Made a fork for my own needs, use it, and not maintain it later.
2. Made a PR to give an opportunity to improve base library. And I am very grateful to @xuri that he was accepted my PRs.

Also I was not planed deep refactoring, but unfortunately `excelize` code is very linked together (IMHO). All minor changes what I done only gave me an errors in very unexpected places.

And panics is the only try to minimise interface changes and spot logic errors (this is not about BC, but about minimising hand-rewrites of depended code).
I agreed that using errors will be much-much better.

@xuri That do you this about all of it?
There is balance for you and your library between speed (and risks) of library growing and stability?

**Comment by albenik** [comment] 2019-03-21 16:36
> The difference between what this library is doing and the regexp library though is that ColumnNumberToName is more of an array access by index while regexp is dynamically building a state machine from a string for a regular grammar. If you access an invalid array index Go panics, I think that would be reasonable to expect here as well.

@mlh758 I have another description: The common part of this library and **regexp** is a syntax check of provided string.
And more than one use-case possible for `ColumnNumberToName` and depended functions.

* First — internal use with basic confidence that all the cell names are correct. So panics is a good way to shorten a code but give a chance to detect typo or another code error.
* Second — accepting external input (cell name) from user. And in this case error return is preferred.

So I think that use of the combined approach (basic functions returns error plus `Must*` wrappers) is justified.

At least we need a separate public functions for column name, row number and cell name validations.

**Comment by mlh758** [comment] 2019-03-21 17:42
I still don't quite agree with you here:

> The common part of this library and regexp is a syntax check of provided string.

There isn't a syntax check in this library, it's performing an array boundary check for valid columns. I would expect the consuming library to sanity check input from the user before passing it on to library code.

ColumnNameToNumber, where the input can be an arbitrary string, makes sense to do this pattern on, and it looks like you already did that in your PR. I'm perfectly happy with the implementation as it is in that direction.

**Comment by albenik** [comment] 2019-03-22 12:41
> I still don't quite agree with you here

@mlh758 Ok, do you accept logic like this one?

1. `IsCollumnNameCorrect(string) bool`, `IsRowNumberCorrect(int) bool`, `IsCellNameCorect(string) bool` added.
2. All other sheet manipulation functions and, and coordinate conversion functions returns only result (if no other errors no related with cell naming needed), and panics with incorrect cell/сol/row input.
3. Cell addressing should be checked in (1) not only for syntax and lower bound but also for hight bounds (like ~16,000)

**Comment by mlh758** [comment] 2019-03-22 13:10
I hadn't thought of adding validation functions, but I do prefer that.

Could the names be `IsValidColumnName` and similar, since they're doing validation?

Also, this is my preference, but if I'm alone here it's not like I'm going to stop using the library or contributing if you stick with the error strategy. I'll just open a PR with the `Must*` style functions you suggested earlier.

**Comment by albenik** [comment] 2019-03-22 13:42
> Could the names be IsValidColumnName and similar, since they're doing validation?

Yes of course, I think.
And I will be glad to hear @xuri opinion.

> Also, this is my preference, but if I'm alone here it's not like I'm going to stop using the library or contributing if you stick with the error strategy. I'll just open a PR with the Must* style functions you suggested earlier.

And again @xuri opinion will be most important, I think.

For me, both ways (with errors and `Must` wrappers and with panics) are acceptable.

**Comment by albenik** [comment] 2019-03-26 07:54
@mlh758 As of commit https://github.com/360EntSecGroup-Skylar/excelize/commit/40ff5dc1a7d7aa42f5db9cf9dfe858cc3820b44e I think @xuri decided to use a error returning way....

**Comment by mlh758** [comment] 2019-03-27 13:07
Yup, I'll get a PR up in the near future with some Must methods.
