### ISSUE TITLE
Use same code to generate a xlsx, and the data of xlsx in bytes is not same.

### ISSUE THREAD

**Issue by xtutu** [360EntSecGroup-Skylar/excelize#159] opened 2017-11-21 03:11 UTC
It is not friendly to git. 
Everty time i run the code, i got a modify in git...
Is there any way to solve it?

for example:  
```go
func TestWrite(t *testing.T){
	xlsx := excelize.NewFile()
	xlsx.SetCellValue("Sheet1", "B2", 100)
	err := xlsx.SaveAs("./Write.xlsx")
	if err != nil {
		fmt.Println(err)
	}
}


/*first time data like this
504b 0304 1400 0800 0800 0000 0000 0000
0000 0000 0000 0000 0000 1300 0000 786c
2f74 6865 6d65 2f74 6865 6d65 312e 786d
6cec 99cf 6fdb 3614 c7ef fb2b 08de 57c9
3f64 c741 9522 b1e3 766b d216 8ddb a1c7
6789 9658 53a4 40d2 497c 1bda d32e 0306
/*
/* second time data...
504b 0304 1400 0800 0800 0000 0000 0000
0000 0000 0000 0000 0000 0f00 0000 786c
2f77 6f72 6b62 6f6f 6b2e 786d 6c8c 92cf
6edb 300c c6ef 7b0a 81f7 c652 9006 4160
b9c0 b00d cb65 08b0 ae3d 2b12 1d13 d11f
4392 9be4 ed07 394d e3a2 979c 2851 f68f
....
*/
```

**Comment by xuri** [comment] 2017-11-21 03:44
Thanks for your issue. The binary data generated each time are different. That's inevitable. Try specifies a pattern in the `.gitignore` file if possible.

**Comment by xtutu** [comment] 2017-11-21 04:26
is there any plan to fixed it？
i need add the generate xlsx in git...

**Comment by xuri** [comment] 2017-11-21 04:32
Even using Excel application to generate the same content file binary data each time is still different. I think that's not a bug, so won't fix.

**Comment by xtutu** [comment] 2017-11-21 04:49
好的。

**Closed** 2019-10-27 09:02 UTC
